language: rust

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y apt-transport-https
    - sudo apt-get install -y libstdc++6-4.9 libgomp1-4.9
    - wget https://apt.z.cash/pool/main/z/zcash/zcash-1.0.7-1-amd64.deb
    - sudo dpkg -i zcash-1.0.7-1-amd64.deb
    - zcashd --regtest
