language: rust
cache: cargo

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y apt-transport-https
    - wget https://apt.z.cash/pool/main/z/zcash/zcash-1.0.7-1-amd64.deb
    - sudo dpkg -i zcash-1.0.7-1-amd64.deb
    - mkdir /home/travis/.zcash
    - cp tests/zcash.conf /home/travis/.zcash/
    - zcash-fetch-params
    - zcashd --daemon

before_script:
    - export PATH="$PATH:$HOME/.cargo/bin"
    - which rustfmt || cargo install rustfmt

script:
    - cargo fmt -- --write-mode=diff
    - cargo build
    - cargo test
