language: rust

before_script:
    - sudo apt-get install -qq apt-transport-https
    - wget -qO - https://apt.z.cash/zcash.asc | sudo apt-key add -
    - echo "deb [arch=amd64] https://apt.z.cash/ jessie main" | sudo tee /etc/apt/sources.list.d/zcash.list
    - sudo apt-get update -qq
    - sudo apt-get install -qq zcash
    - zcashd --regtest
