[package]
name = "zcash"
version = "0.1.0"
authors = ["Durga <DurgaMa@users.noreply.github.com>"]
description = "Rust implementation of Zcash CLI and API"

homepage = "https://github.com/DurgaMa/rust-zcash"
repository = "https://github.com/DurgaMa/rust-zcash"

readme = "README.md"
license = "Unlicense"

[[bin]]
name = "zclash-cli"

[dependencies]
